VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('24')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('08')
MAJOR_VERSION = 1
MINOR_VERSION = 13
PATCH_VERSION = 202305241008
version_date = '2023/05/24 10:08'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
