# Generated by Django 4.1.9 on 2023-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cisco_support_plugin', '0004_ciscosupport_api_status_ciscosupport_coverage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciscosupport',
            name='current_release',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='desired_release',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='recommended_release',
            field=models.TextField(blank=True, null=True),
        ),
    ]