# Generated by Django 4.1.9 on 2023-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cisco_support_plugin', '0003_ciscodevicetypesupport_eox_announcement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciscosupport',
            name='api_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='coverage_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]