from typing import List, Optional, Tuple
from numpy import ndarray

def brute_force_location(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> Tuple[ndarray, ndarray]: ...

def brute_force_index(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> Tuple[ndarray, ndarray]: ...

def kd_tree_location(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> Tuple[ndarray, ndarray]: ...

def kd_tree_index(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> Tuple[ndarray, ndarray]: ...
