# Generated by Django 3.2.16 on 2023-01-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_registration', '0020_auto_20210715_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20230126090321', max_length=50),
        ),
    ]
