VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('24')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('59')
MAJOR_VERSION = 0
MINOR_VERSION = 30
PATCH_VERSION = 202305240959
version_date = '2023/05/24 09:59'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
