# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.7'
git_version = '2167700ba3e705e68178ff4f3fc2c7f63d5c9e55'
extra_version_info = ''
enable_trt_backend = 'OFF'
enable_paddle_backend = 'ON'
with_gpu = 'OFF'
