# Generated by Django 2.2.8 on 2020-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0059_auto_20200211_1049'),
        ('webservice', '0003_add_device_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webserviceaction',
            name='webservice_variables',
        ),
        migrations.AddField(
            model_name='webserviceaction',
            name='variables',
            field=models.ManyToManyField(to='pyscada.Variable'),
        ),
    ]
