# coding: utf-8

"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


RequiredGetAccountResponse = TypedDict("RequiredGetAccountResponse", {
    })

OptionalGetAccountResponse = TypedDict("OptionalGetAccountResponse", {
    "name": str,

    "account_number": str,

    "bvn": str,

    "account_type": str,

    "currency": str,

    "account_status": str,

    "balance": str,
    }, total=False)

class GetAccountResponse(RequiredGetAccountResponse, OptionalGetAccountResponse):
    pass
