class UniHub:
    ZJU = 'Zhejiang University'
    PKU = 'Peking University'
    THU = 'Tsinghua University'
    SJTU = 'Shanghai Jiao Tong University'
    FDU = 'Fudan University'
    SYSU = 'Sun Yat-sen University'
    WHU = 'Wuhan University'
    HUST = 'Huazhong University of Science and Technology'
    XJTU = 'Xi\'an Jiaotong University'

    HKU = 'The University of Hong Kong'
    CUHK = 'The Chinese University of Hong Kong'
    HKUST = 'The Hong Kong University of Science and Technology'
    HKBU = 'Hong Kong Baptist University'
    POLYU = 'The Hong Kong Polytechnic University'
    CITYU = 'City University of Hong Kong'

    NTU = 'Nanyang Technological University'
    NUS = 'National University of Singapore'
    SMU = 'Singapore Management University'

    UCL = 'University College London'
    OXFORD = 'University of Oxford'
    CAMBRIDGE = 'University of Cambridge'
    IMPERIAL = 'Imperial College London'
    GLASGOW = 'University of Glasgow'
    EDINBURGH = 'University of Edinburgh'
    MANCHESTER = 'University of Manchester'
    WARWICK = 'University of Warwick'
    YORK = 'University of York'

    STANFORD = 'Stanford University'
    HARVARD = 'Harvard University'
    MIT = 'Massachusetts Institute of Technology'
    CALTECH = 'California Institute of Technology'
    PRINCETON = 'Princeton University'
    YALE = 'Yale University'
    UCB = 'University of California, Berkeley'
    UCHICAGO = 'University of Chicago'
    COLUMBIA = 'Columbia University'
    UPENN = 'University of Pennsylvania'
    CORNELL = 'Cornell University'
    JOHNSHOPKINS = 'Johns Hopkins University'
    UTAUSTIN = 'University of Texas at Austin'

