
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-25T11:06:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "42270077eb98274719403894626f8eef2f71425a",
 "version": "1.13.211"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
