VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('25')
VERSION_HOUR = int('00')
VERSION_MINUTE = int('48')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202305250048
version_date = '2023/05/25 00:48'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
