# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cyberpay_utils/task/proto/task_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,cyberpay_utils/task/proto/task_service.proto\"\xfa\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x18\n\x0b\x64\x65scription\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05price\x18\x05 \x01(\t\x12\x11\n\tfrom_date\x18\x06 \x01(\t\x12\x0f\n\x07to_date\x18\x07 \x01(\t\x12\x14\n\x0cis_completed\x18\x08 \x01(\x08\x12\x0f\n\x07is_paid\x18\t \x01(\x08\x12\x11\n\tis_signed\x18\n \x01(\x08\x12\r\n\x05state\x18\x0b \x01(\t\x12\x18\n\x10payment_datetime\x18\x0c \x01(\t\x12\x17\n\x0f\x63ompany_user_id\x18\r \x01(\x05\x42\x0e\n\x0c_description\"\xcf\x01\n\x0fGetTasksRequest\x12\x17\n\ncompany_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x14\n\x07user_id\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x19\n\x0cis_completed\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x14\n\x07is_paid\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x16\n\tis_signed\x18\x05 \x01(\x08H\x04\x88\x01\x01\x42\r\n\x0b_company_idB\n\n\x08_user_idB\x0f\n\r_is_completedB\n\n\x08_is_paidB\x0c\n\n_is_signed\"(\n\x10GetTasksResponse\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task2C\n\x0eTaskController\x12\x31\n\x08GetTasks\x12\x10.GetTasksRequest\x1a\x11.GetTasksResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cyberpay_utils.task.proto.task_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASK._serialized_start=49
  _TASK._serialized_end=299
  _GETTASKSREQUEST._serialized_start=302
  _GETTASKSREQUEST._serialized_end=509
  _GETTASKSRESPONSE._serialized_start=511
  _GETTASKSRESPONSE._serialized_end=551
  _TASKCONTROLLER._serialized_start=553
  _TASKCONTROLLER._serialized_end=620
# @@protoc_insertion_point(module_scope)
