
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-27T14:42:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b60b5db205fbf57a12d197b4d9c02c89264ead0b",
 "version": "0.1.0-rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
