# Generated by Django 4.2 on 2023-04-26 10:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('multistepform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
