# Generated by Django 4.2 on 2023-05-26 09:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('multistepform', '0002_alter_formfield_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='meta_data',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
