# coding: utf-8

"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


RequiredDeleteWebhookResponse = TypedDict("RequiredDeleteWebhookResponse", {
    })

OptionalDeleteWebhookResponse = TypedDict("OptionalDeleteWebhookResponse", {
    "entity": str,
    }, total=False)

class DeleteWebhookResponse(RequiredDeleteWebhookResponse, OptionalDeleteWebhookResponse):
    pass
