# -*- coding: utf-8 -*-

"""
oceanxbridgeplatformapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TimezonesEnum(object):

    """Implementation of the 'timezones' enum.

    Description: 
      List of valid timezones used to adjust reporting by.
    > Status:
      * `CT` - Central Time
      * `ET` - Eastern Time
      * `MT` - Mountain Time
      * `PT` - Pacific  Time
    >

    Attributes:
        CT: TODO: type description here.
        ET: TODO: type description here.
        MT: TODO: type description here.
        PT: TODO: type description here.

    """

    CT = 'CT'

    ET = 'ET'

    MT = 'MT'

    PT = 'PT'
