# Generated by Django 2.2 on 2020-02-19 09:49

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_observation', '0002_auto_20190611_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='_comment_excerpt',
            field=models.TextField(default='empty', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='comment',
            field=model_utils.fields.SplitField(no_excerpt_field=True, verbose_name='Comment'),
        ),
    ]
