
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-23T13:30:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b52676010f1b214866ef21552d3fcb4c6d72e13",
 "version": "3.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
