
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-25T10:20:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b7557600617003b817bc5e08726d20620e59247",
 "version": "0.0.173"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
