from Numtoname.functions import generate_name_fixed
from Numtoname.functions import generate_names_fixed
from Numtoname.functions import generate_name
from Numtoname.functions import generate_names
from Numtoname.functions import generate_name_fixed_alpha
from Numtoname.functions import generate_names_fixed_alpha
from Numtoname.functions import generate_name_alpha
from Numtoname.functions import generate_names_alpha
from Numtoname.functions import generate_name_fixed_alpha2
from Numtoname.functions import generate_names_fixed_alpha2
from Numtoname.functions import generate_name_alpha2
from Numtoname.functions import generate_names_alpha2
