# Generated by Django 2.2.8 on 2020-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webserviceaction',
            name='variables',
        ),
        migrations.AddField(
            model_name='webserviceaction',
            name='webservice_variables',
            field=models.ManyToManyField(to='webservice.WebServiceVariable'),
        ),
        migrations.AlterField(
            model_name='webserviceaction',
            name='path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
