# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from dojah_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    API_V1_GH_KYC_DL = "/api/v1/gh/kyc/dl"
    API_V1_GH_KYC_PASSPORT = "/api/v1/gh/kyc/passport"
    API_V1_GH_KYC_SSNIT = "/api/v1/gh/kyc/ssnit"
    API_V1_UG_KYC_VOTER = "/api/v1/ug/kyc/voter"
    API_V1_KE_KYC_ID = "/api/v1/ke/kyc/id"
    API_V1_KYC_DL = "/api/v1/kyc/dl"
    API_V1_KYC_NUBAN = "/api/v1/kyc/nuban"
    API_V1_KYC_BVN = "/api/v1/kyc/bvn"
    API_V1_KYC_BVN_BASIC = "/api/v1/kyc/bvn/basic"
    API_V1_KYC_BVN_FULL = "/api/v1/kyc/bvn/full"
    API_V1_KYC_BVN_ADVANCE = "/api/v1/kyc/bvn/advance"
    API_V1_KYC_VNIN = "/api/v1/kyc/vnin"
    V1_KYC_PHONE_NUMBER_BASIC = "/v1/kyc/phone_number/basic"
    API_V1_KYC_PHONE_NUMBER = "/api/v1/kyc/phone_number"
    V1_KYC_AGE_VERIFICATION = "/v1/kyc/age_verification"
    V1_KYC_BVN_VERIFY = "/v1/kyc/bvn/verify"
    V1_KYC_NIN_VERIFY = "/v1/kyc/nin/verify"
    API_V1_KYC_VIN = "/api/v1/kyc/vin"
    V1_KYC_EMAIL = "/v1/kyc/email"
    API_V1_KYC_PASSPORT = "/api/v1/kyc/passport"
    API_V1_DOCUMENT_ANALYSIS = "/api/v1/document/analysis"
    V1_KYC_CAC = "/v1/kyc/cac"
    V1_KYC_CAC_BASIC = "/v1/kyc/cac/basic"
    V1_KYC_CAC_ADVANCE = "/v1/kyc/cac/advance"
    V1_KYC_TIN = "/v1/kyc/tin"
    API_V1_MESSAGING_SMS = "/api/v1/messaging/sms"
    V1_MESSAGING_SMS_GET_STATUS = "/v1/messaging/sms/get_status"
    V1_MESSAGING_OTP = "/v1/messaging/otp"
    V1_MESSAGING_OTP_VALIDATE = "/v1/messaging/otp/validate"
    API_V1_MESSAGING_SENDER_IDS = "/api/v1/messaging/sender_ids"
    API_V1_MESSAGING_SENDER_ID = "/api/v1/messaging/sender_id"
    V1_WALLET_NGN_CREATE = "/v1/wallet/ngn/create"
    V1_WALLET_NGN_RETRIEVE = "/v1/wallet/ngn/retrieve"
    V1_WALLET_NGN_ACCOUNTS = "/v1/wallet/ngn/accounts"
    V1_WALLET_NGN_TRANSACTION = "/v1/wallet/ngn/transaction"
    V1_WALLET_NGN_TRANSFER = "/v1/wallet/ngn/transfer"
    V1_WALLET_NGN_CREDIT = "/v1/wallet/ngn/credit"
    API_V1_FINANCIAL_ACCOUNT_TRANSACTIONS = "/api/v1/financial/account_transactions"
    V1_FINANCIAL_ACCOUNT_SUBSCRIPTION = "/v1/financial/account_subscription"
    V1_FINANCIAL_BVN_INFORMATION_BASIC = "/v1/financial/bvn_information/basic"
    V1_FINANCIAL_BVN_INFORMATION_FULL = "/v1/financial/bvn_information/full"
    V1_FINANCIAL_SPENDING_PATTERN = "/v1/financial/spending_pattern"
    V1_FINANCIAL_EARNING_STRUCTURE = "/v1/financial/earning_structure"
    V1_FINANCIAL_TRANSACTIONS = "/v1/financial/transactions"
    API_V1_FINANCIAL_TRANSACTIONS_PDF = "/api/v1/financial/transactions/pdf"
    API_V1_FINANCIAL_ANALYSIS = "/api/v1/financial/analysis"
    V1_KYC_PHOTOID_VERIFY = "/v1/kyc/photoid/verify"
    V1_ML_OCR = "/v1/ml/ocr"
    V1_ML_OCR_GENERIC = "/v1/ml/ocr/generic"
    V1_DOCUMENT_ANALYSIS_DL = "/v1/document/analysis/dl"
    API_V1_AML_SCREENING = "/api/v1/aml/screening"
    V1_AML_SCREENING_INFO = "/v1/aml/screening/info"
    API_V1_BALANCE = "/api/v1/balance"
    V1_PURCHASE_AIRTIME = "/v1/purchase/airtime"
    V1_PURCHASE_DATA = "/v1/purchase/data"
    V1_PURCHASE_DATA_PLANS = "/v1/purchase/data/plans"
    V1_GENERAL_BANKS = "/v1/general/banks"
    V1_GENERAL_ACCOUNT = "/v1/general/account"
    V1_GENERAL_BIN = "/v1/general/bin"
    V1_ML_CATEGORIZE_TRANSACTION = "/v1/ml/categorize_transaction"
    API_V1_WEBHOOK_SUBSCRIBE = "/api/v1/webhook/subscribe"
    API_V1_WEBHOOK_DELETE = "/api/v1/webhook/delete"
    API_V1_WEBHOOK_FETCH = "/api/v1/webhook/fetch"
    API_V1_WEBHOOK_NOTIFY = "/api/v1/webhook/notify"
    API_V1_FINANCIAL_ACCOUNT_INFORMATION = "/api/v1/financial/account_information"
