Q_LIST_SOCIO_CNPJ = """
SELECT [NUM_CNPJ_EMPRESA]
    ,[IND_TIPO]
    ,[NUM_CPF]
    ,[NUM_CNPJ]
    ,[NOME]     
    ,[DATA_ENTRADA_SOCIEDADE]
    ,[DATA_DE_EXCLUSAO_NA_SOCIEDADE]
    ,MAX(socio.VERSAO_REGISTRO) AS VERSAO_REGISTRO
FROM [TRILHAS_AUDITORIA].[dbo].[trilhas_socio] AS socio
WHERE socio.NUM_CNPJ_EMPRESA IN ('{cnpj_list}')
    AND socio.DATA_ENTRADA_SOCIEDADE <= '{data_entrada}' AND
    (socio.DATA_DE_EXCLUSAO_NA_SOCIEDADE IS NULL AND socio.FLAG_VIGENTE = 1 OR
    socio.DATA_DE_EXCLUSAO_NA_SOCIEDADE > '{data_saida}')
GROUP BY [NUM_CNPJ_EMPRESA]
    ,[IND_TIPO]
    ,[NUM_CPF]
    ,[NUM_CNPJ]
    ,[NOME]      
    ,[DATA_ENTRADA_SOCIEDADE]
    ,[DATA_DE_EXCLUSAO_NA_SOCIEDADE]
"""
