"""
Store constants that define color cycles for the plots
"""
PALETTS = {'blue-green': ['blue',
                          'dodgerblue',
                          'lightskyblue',
                          'cyan',
                          'lightseagreen',
                          'mediumspringgreen',
                          'lawngreen',
                          'lime'],
           'green-yellow': ['darkgreen',
                            'green',
                            'limegreen',
                            'lime',
                            'lawngreen',
                            'greenyellow',
                            'yellowgreen',
                            'olivedrap',
                            'darkolivegreen'],
           'red-yellow': ['firebrick',
                          'lightcoral',
                          'coral',
                          'orangered',
                          'red',
                          'darkorange',
                          'orange',
                          'gold',
                          'goldenrod'],
           'green-blue-magenta': ['lime',
                                  'springgreen',
                                  'mediumspringgreen',
                                  'aquamarine',
                                  'aqua',
                                  'deepskyblue',
                                  'dodgerblue',
                                  'royalblue',
                                  'blue',
                                  'mediumslateblue',
                                  'blueviolet',
                                  'magenta',
                                  'deeppink',
                                  ],
           'green-blue-magenta-fast': ['limegreen',
                                       'mediumspringgreen',
                                       'aqua',
                                       'dodgerblue',
                                       'blue',
                                       'blueviolet',
                                       'magenta',
                                       'deeppink'], }
