
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-26T15:23:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e06c9c267da07803c78d821c4d6e71bb5596f504",
 "version": "0.3.0.post0.dev30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
