# coding: utf-8

"""
    Humanloop API

    The Humanloop API allows you to interact with Humanloop from your product or service.  You can do this through HTTP requests from any language or via our official Python SDK.  To install the official Python SDK, run the following command:  ```bash pip install humanloop ```  ---  Guides and further details about key concepts can be found in [our docs](https://humanloop.gitbook.io/humanloop-docs/).

    The version of the OpenAPI document: 4.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from humanloop import schemas  # noqa: F401


class ModelEndpoints(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Supported model provider endpoints.
    """


    class MetaOapg:
        enum_value_to_name = {
            "complete": "COMPLETE",
            "chat": "CHAT",
            "edit": "EDIT",
        }
    
    @schemas.classproperty
    def COMPLETE(cls):
        return cls("complete")
    
    @schemas.classproperty
    def CHAT(cls):
        return cls("chat")
    
    @schemas.classproperty
    def EDIT(cls):
        return cls("edit")
