# coding: utf-8

"""
    Humanloop API

    The Humanloop API allows you to interact with Humanloop from your product or service.  You can do this through HTTP requests from any language or via our official Python SDK.  To install the official Python SDK, run the following command:  ```bash pip install humanloop ```  ---  Guides and further details about key concepts can be found in [our docs](https://humanloop.gitbook.io/humanloop-docs/).

    The version of the OpenAPI document: 4.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


class RequiredProjectUserResponse(TypedDict):
    # String ID of user. Starts with `usr_`.
    id: str

    # The user's email address.
    email_address: str

class OptionalProjectUserResponse(TypedDict, total=False):
    # The user's full name.
    full_name: str

class ProjectUserResponse(RequiredProjectUserResponse, OptionalProjectUserResponse):
    pass
