__version__ = '0.1.7'
__name__ = 'tk_cbed'
__description__ = 'Advanced 4D-STEM Ptychography: Neural Networks for Precise CBED Alignment and Restoration'
__author__ = 'Ivan Lobato'
__author_email__='ivanlh20@gmail.com'
__url__ = 'https://github.com/Ivanlh20/tk_cbed/'
__credits__ = 'The Rosalind Franklin Institute'
__license__ = 'GPLv3'