from setuptools import setup,find_packages

setup(
    name='eobi',
    version='1.1.4',
    description='...',
    author='Autogon Inc',
    author_email='developer@autogon.ai',
    packages=find_packages(),
    install_requires=[
            'catboost',
            'contourpy',
            'cycler',
            'fonttools',
            'graphviz',
            'joblib',
            'kiwisolver',
            'lightgbm',
            'matplotlib',
            'numpy',
            'packaging',
            'pandas',
            'Pillow',
            'plotly',
            'pyparsing',
            'python-dateutil',
            'pytz',
            'scikit-learn',
            'scipy',
            'six',
            'tenacity',
            'threadpoolctl',
            'tzdata',
            'xgboost',
            'dataprep',
            'py-AutoClean'
    ],
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)
