PRODUCT_FLOW_KIND = 'smart-feeds-product-flow'
PEFORMANCE_DASHBOARD_KIND = 'performance-dashboard'
DATA_EXPORT_KIND = 'smart-feeds-data-exports'
DATA_INGESTION_KIND = 'smart-feeds-data-ingestions'
DATA_PROCESSING_KIND = 'smart-feeds-data-processings'
PROTECTION_KIND = 'protection-file-size'
ALERT_KIND = 'alert-file-change'
