
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-24T11:01:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7419837fbbdc9b54df4337848e8f4eabd835c6bc",
 "version": "0.3.0.post0.dev26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
