# Generated by Django 4.1.9 on 2023-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_cisco_support_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciscodevicetypesupport",
            name="eox_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
