from .downloadimgs import downloadallimg
from .isevenodd import iseven,isodd
from .isprime import isprime
from .listlink import listlink
from .ping import ping
from .removelistduplicate import listremoveduplicate
from .reportfile import reportfile
from .singledownload import imgsingledownload
from .stringalowerupper import stringlower,stringUPPER
