VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('25')
VERSION_HOUR = int('01')
VERSION_MINUTE = int('18')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202305250118
version_date = '2023/05/25 01:18'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
